### ISSUE TITLE
Make the library "nullsafe"?

### ISSUE THREAD

**Issue by vn971** [mrbech/match#13]
Hi! Is it possible to make the library "nullsafe"?

I found the library to be really cool, considering using that even though it's pre-1.0 and not much "github-starred" yet. But it seems really good!

**Comment by mrbech** [comment]
Hey :) Sorry for the delayed response. I have upgraded to null safety in https://github.com/mrbech/match/pull/14 and released a version `0.4.0` with the changes.

At this stage it's probably only the app I am working on using the library, it's been stable for a while because I hadn't discovered any things I personally needed changed for my application. I try to keep the library updated, but hadn't personally gotten around to the null safety upgrade yet :)

If you have any questions or run into any issues feel free to open issues here on Github :)

**Comment by vn971** [comment]
Thank you!
